[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]] 
repo = 'Shougo/neosnippet'

[[plugins]] 
repo = 'Shougo/neosnippet-snippets'

[[plugins]] 
repo = 'szw/vim-tags'

[[plugins]] 
repo = 'tpope/vim-endwise'

[[plugins]] 
repo = 'todesking/ruby_hl_lvar.vim'
