# pythonの補完
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']

# vimのpythonにpyenvのpythonを使えるようにする
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['davidhalter/jedi-vim']
on_ft = ['python', 'python3']

# snippetを追加
[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
